#!/bin/bash

#COMPONENT="TestComponentA"
COMPNAME="Documentation"
COMPIMPACT="major"
SERVICEDESC="http status"
SERVICESTATE="CRITICAL"
SERVICESTATETYPE="HARD"
SERVICEOUTPUT="404 page not found"

./cachet_handler.pl "$COMPNAME" "$COMPIMPACT" "$SERVICEDESC" "$SERVICESTATE" "$SERVICESTATETYPE" "$SERVICEOUTPUT"
